import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const menuItems = [
  // Snacks
  {
    name: 'Kachori',
    category: 'snacks',
    description: 'Crispy fried pastry filled with spiced moong dal and potatoes',
    price: 50,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 120,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 10,
    availability: true,
  },
  {
    name: 'Mirchi Vada',
    category: 'snacks',
    description: 'Green chili stuffed with potato and spices, deep fried until golden',
    price: 45,
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 95,
    isVegetarian: true,
    spiceLevel: 'hot',
    preparationTime: 12,
    availability: true,
  },
  {
    name: 'Sev Puri',
    category: 'snacks',
    description: 'Crispy puri with boiled potatoes, chickpeas, onions and sev topped with chutneys',
    price: 60,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 110,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 8,
    availability: true,
  },
  {
    name: 'Dahi Puri',
    category: 'snacks',
    description: 'Crispy puris filled with potato, chickpeas, onions and topped with yogurt and tamarind chutney',
    price: 55,
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 105,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 9,
    availability: true,
  },
  {
    name: 'Pani Puri',
    category: 'snacks',
    description: 'Hollow crispy puris filled with spiced potato, chickpeas, onions and flavored water',
    price: 50,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 150,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 7,
    availability: true,
  },
  {
    name: 'Moong Dal Pakoda',
    category: 'snacks',
    description: 'Crispy deep-fried fritters made with moong dal, onions and spices',
    price: 40,
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=500&h=500&fit=crop',
    rating: 4.2,
    reviewCount: 80,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 10,
    availability: true,
  },
  {
    name: 'Aloo Tikki',
    category: 'snacks',
    description: 'Crispy potato patties served with tangy chutneys and yogurt',
    price: 55,
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&h=500&fit=crop',
    rating: 4.3,
    reviewCount: 70,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 6,
    availability: true,
  },
  {
    name: 'Samosa',
    category: 'snacks',
    description: 'Crispy triangular pastry filled with spiced potatoes and peas',
    price: 35,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 200,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 8,
    availability: true,
  },
  {
    name: 'Bhel Puri',
    category: 'snacks',
    description: 'Puffed rice mixed with vegetables and tangy tamarind sauce',
    price: 45,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 95,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 5,
    availability: true,
  },
  {
    name: 'Vada Pav',
    category: 'snacks',
    description: 'Mumbai style potato fritter sandwich with spicy chutneys',
    price: 50,
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 180,
    isVegetarian: true,
    spiceLevel: 'hot',
    preparationTime: 8,
    availability: true,
  },
  // Main Course - Curries
  {
    name: 'Chole Bhature',
    category: 'curries',
    description: 'Spiced chickpeas curry served with fluffy deep-fried bread',
    price: 120,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 250,
    isVegetarian: true,
    spiceLevel: 'medium',
    preparationTime: 25,
    availability: true,
  },
  {
    name: 'Dal Tadka',
    category: 'curries',
    description: 'Yellow lentils tempered with cumin, garlic and aromatic spices',
    price: 90,
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 150,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 20,
    availability: true,
  },
  {
    name: 'Paneer Butter Masala',
    category: 'curries',
    description: 'Cottage cheese cubes in rich creamy tomato gravy',
    price: 140,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 200,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 25,
    availability: true,
  },
  {
    name: 'Biryani',
    category: 'curries',
    description: 'Aromatic basmati rice layered with spiced meat and saffron',
    price: 180,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a104?w=500&h=500&fit=crop',
    rating: 4.9,
    reviewCount: 300,
    isVegetarian: false,
    spiceLevel: 'medium',
    preparationTime: 45,
    availability: true,
  },
  {
    name: 'Butter Chicken',
    category: 'curries',
    description: 'Tender chicken in creamy tomato-based rich gravy',
    price: 160,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 280,
    isVegetarian: false,
    spiceLevel: 'mild',
    preparationTime: 30,
    availability: true,
  },
  {
    name: 'Palak Paneer',
    category: 'curries',
    description: 'Cottage cheese cubes in creamy spinach gravy',
    price: 130,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 170,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 25,
    availability: true,
  },
  // Breads
  {
    name: 'Garlic Naan',
    category: 'breads',
    description: 'Soft leavened bread topped with garlic and butter',
    price: 40,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 220,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 10,
    availability: true,
  },
  {
    name: 'Butter Roti',
    category: 'breads',
    description: 'Traditional whole wheat flatbread brushed with butter',
    price: 25,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&h=500&fit=crop',
    rating: 4.4,
    reviewCount: 120,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 8,
    availability: true,
  },
  {
    name: 'Laccha Paratha',
    category: 'breads',
    description: 'Layered flaky flatbread cooked with ghee',
    price: 45,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 150,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 12,
    availability: true,
  },
  // Desserts
  {
    name: 'Gulab Jamun',
    category: 'desserts',
    description: 'Deep-fried milk balls soaked in rose-flavored sugar syrup',
    price: 60,
    image: 'https://images.unsplash.com/photo-1666190094726-7ea83a7c802f?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 200,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 15,
    availability: true,
  },
  {
    name: 'Rasmalai',
    category: 'desserts',
    description: 'Soft cottage cheese dumplings soaked in sweet saffron milk',
    price: 80,
    image: 'https://images.unsplash.com/photo-1571006682359-07895345efc9?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 160,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 20,
    availability: true,
  },
  {
    name: 'Jalebi',
    category: 'desserts',
    description: 'Crispy golden spirals soaked in sugar syrup',
    price: 55,
    image: 'https://images.unsplash.com/photo-1601303516033-a4f2a4b64c09?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 180,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 15,
    availability: true,
  },
  {
    name: 'Kheer',
    category: 'desserts',
    description: 'Creamy rice pudding flavored with cardamom and nuts',
    price: 70,
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 140,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 25,
    availability: true,
  },
  {
    name: 'Gajar Ka Halwa',
    category: 'desserts',
    description: 'Slow-cooked carrot pudding with ghee, milk and nuts',
    price: 75,
    image: 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 120,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 30,
    availability: true,
  },
  // Beverages
  {
    name: 'Masala Chai',
    category: 'beverages',
    description: 'Traditional spiced tea brewed with aromatic spices',
    price: 25,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=500&h=500&fit=crop',
    rating: 4.9,
    reviewCount: 300,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 5,
    availability: true,
  },
  {
    name: 'Mango Lassi',
    category: 'beverages',
    description: 'Creamy yogurt smoothie blended with fresh mango',
    price: 45,
    image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 180,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 5,
    availability: true,
  },
  {
    name: 'Sweet Lassi',
    category: 'beverages',
    description: 'Traditional sweet yogurt drink with cardamom',
    price: 40,
    image: 'https://images.unsplash.com/photo-1571006682359-07895345efc9?w=500&h=500&fit=crop',
    rating: 4.5,
    reviewCount: 130,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 5,
    availability: true,
  },
  // Specialty
  {
    name: 'Pav Bhaji',
    category: 'snacks',
    description: 'Spiced mashed vegetables served with buttered bread rolls',
    price: 90,
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=500&h=500&fit=crop',
    rating: 4.8,
    reviewCount: 220,
    isVegetarian: true,
    spiceLevel: 'hot',
    preparationTime: 20,
    availability: true,
  },
  {
    name: 'Dosa',
    category: 'snacks',
    description: 'Crispy fermented rice and lentil crepe with sambar and chutney',
    price: 80,
    image: 'https://images.unsplash.com/photo-1668184887432-2c9c6a5d5b0a?w=500&h=500&fit=crop',
    rating: 4.7,
    reviewCount: 190,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 15,
    availability: true,
  },
  {
    name: 'Idli Sambar',
    category: 'snacks',
    description: 'Steamed rice cakes served with lentil soup and coconut chutney',
    price: 70,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=500&fit=crop',
    rating: 4.6,
    reviewCount: 150,
    isVegetarian: true,
    spiceLevel: 'mild',
    preparationTime: 12,
    availability: true,
  },
];

async function main() {
  console.log('Start seeding ...');

  const adminPassword = await bcrypt.hash('admin123', 10);
  const customerPassword = await bcrypt.hash('customer123', 10);

  await prisma.user.upsert({
    where: { email: 'admin@dwarkesh.com' },
    update: {},
    create: {
      name: 'Admin User',
      email: 'admin@dwarkesh.com',
      phone: '0571679999',
      password: adminPassword,
      role: 'admin',
      address: 'Dwarkesh Restaurant, Main Street',
      city: 'Ghana',
    },
  });
  console.log('Created admin user: admin@dwarkesh.com');

  await prisma.user.upsert({
    where: { email: 'customer@dwarkesh.com' },
    update: {},
    create: {
      name: 'John Doe',
      email: 'customer@dwarkesh.com',
      phone: '0551234567',
      password: customerPassword,
      role: 'customer',
      address: '123 Main Street, Accra',
      city: 'Accra',
    },
  });
  console.log('Created customer user: customer@dwarkesh.com');

  await prisma.orderItem.deleteMany({});
  await prisma.payment.deleteMany({});
  await prisma.order.deleteMany({});
  await prisma.deliveryTracking.deleteMany({});
  await prisma.menuItem.deleteMany({});

  for (const item of menuItems) {
    const menuItem = await prisma.menuItem.create({
      data: item,
    });
    console.log(`Created menu item: ${menuItem.name}`);
  }

  console.log(`Seeding finished. Created ${menuItems.length} menu items.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
