build:
  command: npm run build
  env:
    - DATABASE_URL
    - JWT_SECRET
    - JWT_EXPIRE
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - MOMO_API_KEY
    - MOMO_API_USER
    - MOMO_ENV
    - FRONTEND_URL
    - NODE_ENV=production

run:
  command: npm start
  env:
    - DATABASE_URL
    - JWT_SECRET
    - JWT_EXPIRE
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - MOMO_API_KEY
    - MOMO_API_USER
    - MOMO_ENV
    - FRONTEND_URL
    - NODE_ENV=production