{
  "build": {
    "builder": "nicksheffield/render-ts",
    "buildCommand": "npm install && npx prisma generate && npm run build",
    "startCommand": "npm start"
  },
  "env": {
    "DATABASE_URL": {
      "sync": false
    },
    "JWT_SECRET": {
      "sync": false
    },
    "JWT_EXPIRE": {
      "sync": false
    },
    "FRONTEND_URL": {
      "sync": false
    },
    "NODE_ENV": {
      "sync": false
    }
  }
}